In [17]:
import numpy as np
import pandas as pd
import csv

Question 4

In [43]:
choice = int(input(prompt = '1 for 1d array. /n 2 for 2d array.'))
n = int(input(prompt = 'enter number of rows : '))
if choice == 2:
    m = int(input(prompt = 'enter number of cols : '))
    batao1 = int(input('1 for array with zeros. /n 2 for array with ones. /n 3 for random array.'))
    if batao1 == 1:
        array1 = np.zeros((n,m), dtype = 'int64')
        print(array1)
    elif batao1 == 2:
        array2 = np.ones((n,m), dtype = 'int64')
        print(array2)
    else:
        array3 = np.random.randint(1,10,(n,m))
        print(array3)
else:
    batao2 = int(input('1 for array with zeros. /n 2 for array with ones. /n 3 for random array.'))
    if batao2 == 1:
        onedarray1 = np.zeros((n), dtype = 'int64')
        print(onedarray1)
    elif batao2 == 2:
        onedarray2 = np.ones((n), dtype = 'int64')
        print(onedarray2)
    else:
        onedarray3 = np.random.randint(1,10,(n))
        print(onedarray3)

1 for 1d array. /n 2 for 2d array.1
enter number of rows : 5
1 for array with zeros. /n 2 for array with ones. /n 3 for random array.2
[1 1 1 1 1]


In [33]:
print(array1,array2,array3)
print(onedarray1,onedarray2,onedarray3)

[[0 0 0]
 [0 0 0]] [[1 1 1]
 [1 1 1]] [[7 6 9]
 [5 8 7]]
[0 0] [1 1] [3 8]


Question 5

In [27]:
with open('iris.csv','r') as f:
    reader = list(csv.reader(f))
    header,values = reader[0],reader[1:]
    print(np.array(header))
    print(np.array(values))

['sepal.length' 'sepal.width' 'petal.length' 'petal.width' 'variety']
[['5.1' '3.5' '1.4' '.2' 'Setosa']
 ['4.9' '3' '1.4' '.2' 'Setosa']
 ['4.7' '3.2' '1.3' '.2' 'Setosa']
 ['4.6' '3.1' '1.5' '.2' 'Setosa']
 ['5' '3.6' '1.4' '.2' 'Setosa']
 ['5.4' '3.9' '1.7' '.4' 'Setosa']
 ['4.6' '3.4' '1.4' '.3' 'Setosa']
 ['5' '3.4' '1.5' '.2' 'Setosa']
 ['4.4' '2.9' '1.4' '.2' 'Setosa']
 ['4.9' '3.1' '1.5' '.1' 'Setosa']
 ['5.4' '3.7' '1.5' '.2' 'Setosa']
 ['4.8' '3.4' '1.6' '.2' 'Setosa']
 ['4.8' '3' '1.4' '.1' 'Setosa']
 ['4.3' '3' '1.1' '.1' 'Setosa']
 ['5.8' '4' '1.2' '.2' 'Setosa']
 ['5.7' '4.4' '1.5' '.4' 'Setosa']
 ['5.4' '3.9' '1.3' '.4' 'Setosa']
 ['5.1' '3.5' '1.4' '.3' 'Setosa']
 ['5.7' '3.8' '1.7' '.3' 'Setosa']
 ['5.1' '3.8' '1.5' '.3' 'Setosa']
 ['5.4' '3.4' '1.7' '.2' 'Setosa']
 ['5.1' '3.7' '1.5' '.4' 'Setosa']
 ['4.6' '3.6' '1' '.2' 'Setosa']
 ['5.1' '3.3' '1.7' '.5' 'Setosa']
 ['4.8' '3.4' '1.9' '.2' 'Setosa']
 ['5' '3' '1.6' '.2' 'Setosa']
 ['5' '3.4' '1.6' '.4' 'Setosa']
 ['5.

In [44]:
# another method
haha = np.loadtxt('iris.csv',delimiter = ',' , dtype = 'str')
haha

array([['"sepal.length"', '"sepal.width"', '"petal.length"',
        '"petal.width"', '"variety"'],
       ['5.1', '3.5', '1.4', '.2', '"Setosa"'],
       ['4.9', '3', '1.4', '.2', '"Setosa"'],
       ['4.7', '3.2', '1.3', '.2', '"Setosa"'],
       ['4.6', '3.1', '1.5', '.2', '"Setosa"'],
       ['5', '3.6', '1.4', '.2', '"Setosa"'],
       ['5.4', '3.9', '1.7', '.4', '"Setosa"'],
       ['4.6', '3.4', '1.4', '.3', '"Setosa"'],
       ['5', '3.4', '1.5', '.2', '"Setosa"'],
       ['4.4', '2.9', '1.4', '.2', '"Setosa"'],
       ['4.9', '3.1', '1.5', '.1', '"Setosa"'],
       ['5.4', '3.7', '1.5', '.2', '"Setosa"'],
       ['4.8', '3.4', '1.6', '.2', '"Setosa"'],
       ['4.8', '3', '1.4', '.1', '"Setosa"'],
       ['4.3', '3', '1.1', '.1', '"Setosa"'],
       ['5.8', '4', '1.2', '.2', '"Setosa"'],
       ['5.7', '4.4', '1.5', '.4', '"Setosa"'],
       ['5.4', '3.9', '1.3', '.4', '"Setosa"'],
       ['5.1', '3.5', '1.4', '.3', '"Setosa"'],
       ['5.7', '3.8', '1.7', '.3', '"Setosa"'],


In [45]:
print(haha.shape)
print('numbe of sizes : ',haha.shape[0])
print('features : ',haha[0])
file = np.savetxt('text.txt',haha,delimiter = ',',fmt = '%s')

(151, 5)
numbe of sizes :  151
features :  ['"sepal.length"' '"sepal.width"' '"petal.length"' '"petal.width"'
 '"variety"']


In [41]:
help(np.savetxt)

Help on function savetxt in module numpy.lib.npyio:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e 