In [8]:
import numpy as np
import time

In [27]:
print('1. addition \n 2. substraction. \n 3. multiplication.')
choice = int(input())
n =  int(input(prompt = 'number of rows ? '))
m =  int(input(prompt = 'number of columns ? '))
matrix1 = np.random.randint(1,10,(n,m))
print(len(matrix1[0]))
matrix2 = np.random.randint(1,10,(n,m))
if choice == 1:
    display(matrix1,matrix2)
    aadd1 = time.time()
    print(matrix1 + matrix2)
    badd1 = time.time()
    print('time time for vectorized : ',badd1-aadd1)
    print('addition using for loop : ')
    aadd2 = time.time()
    resAdd = [[matrix1[i][j] + matrix2[i][j] for j in range(m)] for i in range(n)]
    resAdd = np.array(resAdd)
    badd2 = time.time()
    print('time time for iterated : ',badd2-aadd2)
    
    print(resAdd)
elif choice == 2:
    display(matrix1,matrix2)
    asub1 = time.time()
    print(matrix1 - matrix2)
    print('time time for iterated : ',bsub2-asub2)
    bsub1 = time.time()
    print('time time for vectorized : ',bsub1-asub1)
    print('substraction using for loop : ')
    asub2 = time.time()
    resSub = [[matrix1[i][j] + matrix2[i][j] for j in range(m)] for i in range(n)]
    resSub = np.array(resSub)
    bsub2 = time.time()
    print('time time for iterated : ',bsub2-asub2)
    
else:
    nm =  int(input(prompt = 'number of rows ? '))
    mm =  int(input(prompt = 'number of columns ? '))
    matrixformul = np.random.randint(1,10,(nm,mm))
    display(matrix1,matrixformul)
    if m == nm:
        amul1 = time.time()
        print(np.dot(matrix1,matrixformul))
        bmul1 = time.time()
        print('time time for vectorized : ',bmul1-amul1)
        print('multiplication using for loop :')
        amul2 = time.time()
        temp = np.empty((n,mm))
        for i in range(n):
            for j in range(mm):
                for k in range(nm):
                    temp[i,j] += matrix1[i,k] * matrixformul[k,j]
        print(temp)
        bmul2 = time.time()
        print('time time for iterated : ',bmul2-amul2)
    else:
        print('multiplication is not possible.')

1. addition 
 2. substraction. 
 3. multiplication.
1
number of rows ? 2
number of columns ? 2
2


array([[4, 2],
       [6, 2]])

array([[8, 5],
       [2, 6]])

[[12  7]
 [ 8  8]]
time time for vectorized :  0.00015282630920410156
addition using for loop : 
time time for iterated :  1.5497207641601562e-05
[[12  7]
 [ 8  8]]


In [9]:
dir(time)

['CLOCK_MONOTONIC',
 'CLOCK_MONOTONIC_RAW',
 'CLOCK_PROCESS_CPUTIME_ID',
 'CLOCK_REALTIME',
 'CLOCK_THREAD_CPUTIME_ID',
 '_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'clock_getres',
 'clock_gettime',
 'clock_gettime_ns',
 'clock_settime',
 'clock_settime_ns',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'pthread_getcpuclockid',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname',
 'tzset']